#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /etc/sysconfig/heat-params
    owner: "root:root"
    permissions: "0600"
    content: |
      CGROUP_DRIVER="$CGROUP_DRIVER"
      NETWORK_DRIVER="$NETWORK_DRIVER"
      TLS_DISABLED="$TLS_DISABLED"
      VERIFY_CA="$VERIFY_CA"
      CLUSTER_UUID="$CLUSTER_UUID"
      MAGNUM_URL="$MAGNUM_URL"
      AUTH_URL="$AUTH_URL"
      REGION_NAME="$REGION_NAME"
      HTTP_PROXY="$HTTP_PROXY"
      HTTPS_PROXY="$HTTPS_PROXY"
      NO_PROXY="$NO_PROXY"
      KUBE_TAG="$KUBE_TAG"
      PODS_NETWORK_CIDR="$PODS_NETWORK_CIDR"
      PORTAL_NETWORK_CIDR="$PORTAL_NETWORK_CIDR"
      TRUSTEE_USER_ID="$TRUSTEE_USER_ID"
      TRUSTEE_PASSWORD="$TRUSTEE_PASSWORD"
      TRUST_ID="$TRUST_ID"
      CLOUD_PROVIDER_ENABLED="$CLOUD_PROVIDER_ENABLED"
      INSECURE_REGISTRY_URL="$INSECURE_REGISTRY_URL"
      CONTAINER_INFRA_PREFIX="$CONTAINER_INFRA_PREFIX"
      DNS_SERVICE_IP="$DNS_SERVICE_IP"
      DNS_CLUSTER_DOMAIN="$DNS_CLUSTER_DOMAIN"
      KUBELET_OPTIONS="$KUBELET_OPTIONS"
      KUBEPROXY_OPTIONS="$KUBEPROXY_OPTIONS"
      HEAT_CONTAINER_AGENT_TAG="$HEAT_CONTAINER_AGENT_TAG"
