heat_template_version: 2014-10-16

description: >
  This is a nested stack that defines a single Mesos master, This stack is
  included by a ResourceGroup resource in the parent template
  (mesoscluster.yaml).

parameters:

  server_image:
    type: string
    description: glance image used to boot the server

  master_flavor:
    type: string
    description: flavor to use when booting the server

  ssh_key_name:
    type: string
    description: name of ssh key to be provisioned on our server

  external_network:
    type: string
    description: uuid/name of a network to use for floating ip addresses

  fixed_network:
    type: string
    description: Network from which to allocate fixed addresses.

  fixed_subnet:
    type: string
    description: Subnet from which to allocate fixed addresses.

  secgroup_base_id:
    type: string
    description: ID of the security group for base.

  secgroup_mesos_id:
    type: string
    description: ID of the security group for mesos master.

  api_pool_id:
    type: string
    description: ID of the load balancer pool of Marathon.

resources:

  ######################################################################
  #
  # Mesos master server.
  #

  mesos-master:
    type: OS::Nova::Server
    properties:
      image: {get_param: server_image}
      flavor: {get_param: master_flavor}
      key_name: {get_param: ssh_key_name}
      user_data_format: SOFTWARE_CONFIG
      metadata:
        cern-services: false

outputs:

  mesos_master_ip:
    value: {get_attr: [mesos-master, first_address]}
    description: >
      This is the "private" address of the Mesos master node.
  mesos_master_external_ip:
    value: {get_attr: [mesos-master, first_address]}
    description: >
      This is the "public" address of the Mesos master node.
  mesos_server_id:
    value: {get_resource: mesos-master}
    description: >
      This is the logical id of the Mesos master node.
